### ISSUE TITLE
Add Workflow tab to New Admin Set page

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyku#455]
## Workflow-related decisions made in late October 2016

* Lerna/Sufia ships with a default Admin Set and two available workflows
  * Zero-step, or “direct deposit” (mimicking the current CC/Sufia/Lerna “workflows”)
  * One-step approval workflow
* By default, workflow is zero-step, preserving current behavior of “direct deposit.”
* By default, all works go into the default Admin Set; this way workflows are always attached to Admin Sets and we can rely on every work having an Admin Set.
* Administrative users and their designees can create additional Admin Sets as well (Note: this currently requires setting the `assign_admin_set` flipper on; once we have a default Admin Set, this flipper will no longer be necessary).
  * If additional Admin Sets are not created, the widget that allows assignment to an Admin Set in the Relationships tab of the work creation form should not be rendered (or should be rendered but unselectable?). When they are created, accessible Admin Sets should populate the dropdown.
  * During Admin Set creation, the two pre-baked workflows are available to select from a menu and will be used for every work added to the new Admin Set.
  * Additional workflows beyond the two pre-baked ones can be created and loaded by a programmer following existing documentation, and the application should automatically become aware of new workflows as they are loaded

## Mockup
A new Workflow tab that simply lists each available workflow in a set of radio buttons. The Workflow description is in a paragraph within the label.

![workflow-tab-admin-set](https://cloud.githubusercontent.com/assets/101482/20434630/e3f90572-ad65-11e6-8867-d98ac9e369a8.png)

## Example HTML

```` html
<p>
  Each administrative set has a workflow associated with it. This workflow is applied to all works added to the administrative set. Select the workflow to be used for this administrative set below.
</p>

<div class="form-group workflow-selection">
  <form>
    <fieldset>
      <legend class="sr-only">Workflow</legend>
    <div>
      <input type="radio" name="workflow-type" id="direct" value="direct" checked="checked" />
      <label for="direct">
        <span>Direct Deposit</span>
        <p>A simple workflow where each work is immediately saved, without any mediation steps.</p>
      </label>
    </div>
    <div>
      <input type="radio" name="workflow-type" id="mediated" value="mediated" />
      <label for="mediated">
        <span>Mediated Deposit</span>
        <p>A one-step workflow where each work is first reviewed by a Reviewer, who can approve or reject the work.</p>
      </label>
    </div>
  </fieldset>
  </form>
</div>
````

## Example CSS

```` css
.form-group.workflow-selection {
  margin-left: 20px;
  margin-top: 20px;
}

.workflow-selection label {
  display: block;
  margin-left: 20px;
}

.workflow-selection label > span {
  font-size: 14px;
}

.workflow-selection label > p {
  font-weight: 500;
}

.workflow-selection input[type=radio] {
  float: left;
  margin-right: 10px;
  vertical-align: top;
}
````
